# Generated by Django 6.0.3 on 2026-04-06 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hunter', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='jobapplication',
            new_name='app_owner_created_idx',
            old_name='application_owner_created_at_idx',
        ),
    ]
