# Generated by Django 6.0.3 on 2026-04-11 15:40

import django.db.models.deletion
import hunter.models.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hunter', '0002_rename_application_owner_created_at_idx_app_owner_created_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('file', models.FileField(upload_to=hunter.models.models.resume_upload_to, verbose_name='file')),
                ('original_filename', models.CharField(max_length=255, verbose_name='original filename')),
                ('extracted_text', models.TextField(blank=True, verbose_name='extracted text')),
                ('parse_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20, verbose_name='parse status')),
                ('content_type', models.CharField(max_length=100, verbose_name='content type')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to=settings.AUTH_USER_MODEL, verbose_name='owner')),
            ],
            options={
                'verbose_name': 'resume',
                'verbose_name_plural': 'resumes',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['owner', 'is_active', 'created_at'], name='resume_own_act_idx')],
            },
        ),
    ]
