# Generated by Django 6.0.3 on 2026-04-12 00:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hunter', '0008_resume_product_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('plan_code', models.CharField(default='free', max_length=32, verbose_name='plan code')),
                ('billing_cycle', models.CharField(choices=[('free', 'Free'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], default='free', max_length=16, verbose_name='billing cycle')),
                ('status', models.CharField(choices=[('active', 'Active'), ('canceled', 'Canceled'), ('expired', 'Expired')], default='active', max_length=16, verbose_name='status')),
                ('price_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='price amount')),
                ('currency', models.CharField(default='BRL', max_length=8, verbose_name='currency')),
                ('auto_renew', models.BooleanField(default=True, verbose_name='auto renew')),
                ('started_at', models.DateTimeField(verbose_name='started at')),
                ('current_period_end', models.DateTimeField(blank=True, null=True, verbose_name='current period end')),
                ('canceled_at', models.DateTimeField(blank=True, null=True, verbose_name='canceled at')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='expires at')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_subscriptions', to=settings.AUTH_USER_MODEL, verbose_name='owner')),
            ],
            options={
                'verbose_name': 'billing subscription',
                'verbose_name_plural': 'billing subscriptions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BillingInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('plan_code', models.CharField(default='free', max_length=32, verbose_name='plan code')),
                ('billing_cycle', models.CharField(choices=[('free', 'Free'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], default='free', max_length=16, verbose_name='billing cycle')),
                ('status', models.CharField(choices=[('paid', 'Paid'), ('void', 'Void')], default='paid', max_length=16, verbose_name='status')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='amount')),
                ('currency', models.CharField(default='BRL', max_length=8, verbose_name='currency')),
                ('issued_at', models.DateTimeField(verbose_name='issued at')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='paid at')),
                ('external_reference', models.CharField(blank=True, default='', max_length=64, verbose_name='external reference')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_invoices', to=settings.AUTH_USER_MODEL, verbose_name='owner')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='hunter.billingsubscription', verbose_name='subscription')),
            ],
            options={
                'verbose_name': 'billing invoice',
                'verbose_name_plural': 'billing invoices',
                'ordering': ['-issued_at', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='billingsubscription',
            index=models.Index(fields=['owner', 'status', 'created_at'], name='billsub_owner_status_idx'),
        ),
        migrations.AddIndex(
            model_name='billinginvoice',
            index=models.Index(fields=['owner', 'issued_at'], name='invoice_owner_issued_idx'),
        ),
    ]
