# Generated by Django 6.0.3 on 2026-04-11 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hunter', '0009_billingsubscription_billinginvoice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='billinginvoice',
            name='stripe_invoice_id',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='stripe invoice id'),
        ),
        migrations.AddField(
            model_name='billingsubscription',
            name='stripe_checkout_session_id',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='stripe checkout session id'),
        ),
        migrations.AddField(
            model_name='billingsubscription',
            name='stripe_customer_id',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='stripe customer id'),
        ),
        migrations.AddField(
            model_name='billingsubscription',
            name='stripe_subscription_id',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='stripe subscription id'),
        ),
    ]
