# Generated by Django 6.0.3 on 2026-04-12 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hunter', '0010_stripe_fields_for_billing'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='extraction_diagnostics',
            field=models.JSONField(blank=True, default=dict, verbose_name='extraction diagnostics'),
        ),
    ]
