# Generated by Django 6.0.3 on 2026-04-12 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hunter', '0011_resume_extraction_diagnostics_and_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='parse_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('empty_text', 'Empty Text'), ('scanned_or_image_pdf', 'Scanned Or Image PDF'), ('unsupported_structure', 'Unsupported Structure')], default='pending', max_length=32, verbose_name='parse status'),
        ),
    ]
