# Generated by Django 6.0.3 on 2026-04-16 15:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hunter', '0013_alter_job_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='parse_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('upload_too_large', 'Upload Too Large'), ('invalid_file', 'Invalid File'), ('unsupported_file_type', 'Unsupported File Type'), ('parsing_failed', 'Parsing Failed'), ('parsing_timeout_or_budget_exceeded', 'Parsing Timeout Or Budget Exceeded'), ('empty_text', 'Empty Text'), ('insufficient_text', 'Insufficient Text'), ('scanned_or_image_pdf', 'Scanned Or Image PDF'), ('unsupported_or_unsafe_structure', 'Unsupported Or Unsafe Structure'), ('quarantined_or_blocked_by_policy', 'Quarantined Or Blocked By Policy'), ('failed', 'Failed'), ('unsupported_structure', 'Unsupported Structure')], default='pending', max_length=48, verbose_name='parse status'),
        ),
        migrations.CreateModel(
            name='ProductEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('event_name', models.CharField(db_index=True, max_length=64, verbose_name='event name')),
                ('category', models.CharField(choices=[('journey_milestone', 'Journey milestone'), ('journey_failure', 'Journey failure'), ('technical_failure', 'Technical failure')], max_length=32, verbose_name='category')),
                ('source', models.CharField(blank=True, default='', max_length=64, verbose_name='source')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='metadata')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_events', to=settings.AUTH_USER_MODEL, verbose_name='owner')),
            ],
            options={
                'verbose_name': 'product event',
                'verbose_name_plural': 'product events',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['category', 'event_name', 'created_at'], name='product_event_cat_name_idx'), models.Index(fields=['owner', 'category', 'event_name'], name='product_event_owner_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('category', 'journey_milestone'), ('owner__isnull', False)), fields=('owner', 'category', 'event_name'), name='uniq_owner_journey_milestone')],
            },
        ),
    ]
