# Generated by Codex on 2026-04-16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hunter', '0014_alter_resume_parse_status_productevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='parse_status',
            field=models.CharField(
                choices=[
                    ('pending', 'Pending'),
                    ('processing', 'Processing'),
                    ('completed', 'Completed'),
                    ('upload_too_large', 'Upload Too Large'),
                    ('invalid_file', 'Invalid File'),
                    ('unsupported_file_type', 'Unsupported File Type'),
                    ('parsing_failed', 'Parsing Failed'),
                    ('parsing_timeout_or_budget_exceeded', 'Parsing Timeout Or Budget Exceeded'),
                    ('empty_text', 'Empty Text'),
                    ('insufficient_text', 'Insufficient Text'),
                    ('document_not_resume_like', 'Document Not Resume Like'),
                    ('insufficient_resume_signals', 'Insufficient Resume Signals'),
                    ('blocked_for_low_resume_confidence', 'Blocked For Low Resume Confidence'),
                    ('scanned_or_image_pdf', 'Scanned Or Image PDF'),
                    ('unsupported_or_unsafe_structure', 'Unsupported Or Unsafe Structure'),
                    ('quarantined_or_blocked_by_policy', 'Quarantined Or Blocked By Policy'),
                    ('failed', 'Failed'),
                    ('unsupported_structure', 'Unsupported Structure'),
                ],
                default='pending',
                max_length=48,
                verbose_name='parse status',
            ),
        ),
    ]
