"""
Django settings for project project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
import os
import sys
from datetime import timedelta
from pathlib import Path

import environ

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
TESTING = "test" in sys.argv


# Load environment variables from .env file
env = environ.Env(
    DEBUG=(bool, False)
)
environ.Env.read_env(os.path.join(BASE_DIR, '.env'))


def resolve_path(value: str | os.PathLike[str]) -> Path:
    path = Path(value)
    return path if path.is_absolute() else BASE_DIR / path

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('DJANGO_SECRET_KEY', default='django-insecure-v6m^+o5n4+%-_yxh6-hrt1h(75@lnt%gsng2(!v-kkj!vnx$h(')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool('DJANGO_DEBUG', default=False)

ALLOWED_HOSTS = env.list('ALLOWED_HOSTS', default=['127.0.0.1', 'localhost'] if DEBUG else [])
CSRF_TRUSTED_ORIGINS = env.list("CSRF_TRUSTED_ORIGINS", default=[])
CORS_ALLOWED_ORIGINS = env.list("CORS_ALLOWED_ORIGINS", default=[])
CORS_ALLOW_ALL_ORIGINS = env.bool("CORS_ALLOW_ALL_ORIGINS", default=False)
CORS_ALLOW_CREDENTIALS = env.bool("CORS_ALLOW_CREDENTIALS", default=False)
CORS_ALLOWED_METHODS = env.list(
    "CORS_ALLOWED_METHODS",
    default=["GET", "POST", "PUT", "PATCH", "DELETE", "OPTIONS"],
)
CORS_ALLOWED_HEADERS = env.list(
    "CORS_ALLOWED_HEADERS",
    default=[
        "Authorization",
        "Content-Type",
        "Accept",
        "Origin",
        "User-Agent",
        "DNT",
        "Cache-Control",
        "X-Requested-With",
        "X-CSRFToken",
    ],
)
USE_X_FORWARDED_HOST = env.bool("USE_X_FORWARDED_HOST", default=not DEBUG)
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https") if env.bool("USE_X_FORWARDED_PROTO", default=not DEBUG) else None
SECURE_SSL_REDIRECT = env.bool("DJANGO_SECURE_SSL_REDIRECT", default=False)
SESSION_COOKIE_SECURE = env.bool("SESSION_COOKIE_SECURE", default=not DEBUG)
CSRF_COOKIE_SECURE = env.bool("CSRF_COOKIE_SECURE", default=not DEBUG)
SECURE_HSTS_SECONDS = env.int("SECURE_HSTS_SECONDS", default=0)
SECURE_HSTS_INCLUDE_SUBDOMAINS = env.bool("SECURE_HSTS_INCLUDE_SUBDOMAINS", default=False)
SECURE_HSTS_PRELOAD = env.bool("SECURE_HSTS_PRELOAD", default=False)
APP_BASE_URL = env("APP_BASE_URL", default="http://localhost:8000")
FRONTEND_PUBLIC_URL = env("FRONTEND_PUBLIC_URL", default="http://localhost:3000" if DEBUG else APP_BASE_URL)
SERVE_FRONTEND = env.bool("DJANGO_SERVE_FRONTEND", default=True)
SERVE_MEDIA_FILES = env.bool("DJANGO_SERVE_MEDIA_FILES", default=DEBUG)
FRONTEND_BUILD_DIR = resolve_path(env("FRONTEND_BUILD_DIR", default="frontend_build"))
FRONTEND_INDEX_FILE = FRONTEND_BUILD_DIR / "index.html"
FRONTEND_ASSETS_DIR = FRONTEND_BUILD_DIR / "assets"

if TESTING:
    USE_X_FORWARDED_HOST = False
    SECURE_PROXY_SSL_HEADER = None
    SECURE_SSL_REDIRECT = False
    SESSION_COOKIE_SECURE = False
    CSRF_COOKIE_SECURE = False


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt',
    'django_filters',
    'hunter',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'project.middleware.SimpleCORSMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            BASE_DIR / 'base_template'
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': env.db(default=f"sqlite:///{(BASE_DIR / 'db.sqlite3').as_posix()}"),
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = env("STATIC_URL", default="/static/")
MEDIA_URL = env("MEDIA_URL", default="/media/")
MEDIA_ROOT = resolve_path(env("MEDIA_ROOT", default="media"))
STATIC_ROOT = resolve_path(env("STATIC_ROOT", default="staticfiles"))
STATICFILES_DIRS = []
if (BASE_DIR / "base_static").exists():
    STATICFILES_DIRS.append(BASE_DIR / "base_static")
if FRONTEND_ASSETS_DIR.exists():
    STATICFILES_DIRS.append(("assets", FRONTEND_ASSETS_DIR))
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}
WHITENOISE_MAX_AGE = env.int("WHITENOISE_MAX_AGE", default=31536000)

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.BasicAuthentication',
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_PAGINATION_CLASS': 'hunter.pagination.HunterPagination',
    'PAGE_SIZE': 10,
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ],
    'EXCEPTION_HANDLER': 'project.api_exceptions.product_exception_handler',
}

RESUME_INGESTION = {
    'MAX_UPLOAD_SIZE_BYTES': env.int('RESUME_MAX_UPLOAD_SIZE_BYTES', default=5 * 1024 * 1024),
    'MIN_TRUSTED_TEXT_CHARACTERS': env.int('RESUME_MIN_TRUSTED_TEXT_CHARACTERS', default=15),
    'MIN_TRUSTED_WORDS': env.int('RESUME_MIN_TRUSTED_WORDS', default=3),
    'ALLOWED_EXTENSIONS': ['.pdf', '.docx'],
    'ALLOWED_CONTENT_TYPES': {
        '.pdf': ['application/pdf'],
        '.docx': [
            'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
            'application/zip',
        ],
    },
    'ENABLE_CONTENT_TYPE_VALIDATION': env.bool('RESUME_ENABLE_CONTENT_TYPE_VALIDATION', default=True),
    'ENABLE_PDF_PARSING': env.bool('RESUME_ENABLE_PDF_PARSING', default=True),
    'ENABLE_DOCX_PARSING': env.bool('RESUME_ENABLE_DOCX_PARSING', default=True),
    'ENABLE_PYPDF': env.bool('RESUME_ENABLE_PYPDF', default=True),
    'ENABLE_PDF_REGEX_FALLBACK': env.bool('RESUME_ENABLE_PDF_REGEX_FALLBACK', default=True),
    'ENABLE_PYTHON_DOCX': env.bool('RESUME_ENABLE_PYTHON_DOCX', default=False),
    'PDF_MAX_PAGES': env.int('RESUME_PDF_MAX_PAGES', default=25),
    'PDF_MAX_IMAGES': env.int('RESUME_PDF_MAX_IMAGES', default=128),
    'PDF_MAX_CHARACTERS': env.int('RESUME_PDF_MAX_CHARACTERS', default=120000),
    'DOCX_MAX_ARCHIVE_FILES': env.int('RESUME_DOCX_MAX_ARCHIVE_FILES', default=200),
    'DOCX_MAX_UNCOMPRESSED_BYTES': env.int('RESUME_DOCX_MAX_UNCOMPRESSED_BYTES', default=8 * 1024 * 1024),
    'DOCX_MAX_XML_BYTES': env.int('RESUME_DOCX_MAX_XML_BYTES', default=4 * 1024 * 1024),
    'DOCX_MAX_COMPRESSION_RATIO': env.int('RESUME_DOCX_MAX_COMPRESSION_RATIO', default=100),
}

if TESTING:
    RESUME_INGESTION['MIN_TRUSTED_TEXT_CHARACTERS'] = 15
    RESUME_INGESTION['MIN_TRUSTED_WORDS'] = 3

LOG_LEVEL = env("LOG_LEVEL", default="INFO")
DJANGO_LOG_LEVEL = env("DJANGO_LOG_LEVEL", default="INFO")

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "standard": {
            "format": "%(asctime)s %(levelname)s %(name)s %(message)s",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "standard",
        },
    },
    "root": {
        "handlers": ["console"],
        "level": LOG_LEVEL,
    },
    "loggers": {
        "django": {
            "handlers": ["console"],
            "level": DJANGO_LOG_LEVEL,
            "propagate": False,
        },
    },
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
    'AUTH_HEADER_TYPES': ('Bearer',),
}

JOB_AGGREGATION = {
    'PROVIDER_ORDER': ['remotive', 'greenhouse', 'lever', 'ashby', 'remoteok', 'weworkremotely', 'indeed'],
    'DEFAULTS': {
        'TIMEOUT': 10,
        'MAX_PAGES': 1,
        'MIN_DELAY': 0.0,
        'MAX_DELAY': 0.0,
        'MAX_RETRIES': 2,
        'TRUST_ENV': False,
    },
    'PROVIDERS': {
        'remotive': {
            'ENABLED': True,
            'MAX_PAGES': 1,
            'MIN_DELAY': 0.0,
            'MAX_DELAY': 0.0,
        },
        'greenhouse': {
            'ENABLED': True,
            'BOARD_TOKENS': [
                {'token': 'canonical', 'company': 'Canonical'},
            ],
        },
        'lever': {
            'ENABLED': True,
            'SITES': [
                {'site': 'bighealth', 'company': 'Big Health'},
                {'site': 'dnb', 'company': 'Dun & Bradstreet'},
            ],
        },
        'ashby': {
            'ENABLED': True,
            'JOB_BOARDS': [
                {'board': 'openai', 'company': 'OpenAI'},
            ],
        },
        'remoteok': {
            'ENABLED': False,
            'MAX_PAGES': 1,
            'MIN_DELAY': 0.0,
            'MAX_DELAY': 0.0,
        },
        'weworkremotely': {
            'ENABLED': False,
            'MAX_PAGES': 1,
            'MIN_DELAY': 0.0,
            'MAX_DELAY': 0.0,
        },
        'indeed': {
            'ENABLED': False,
            'MAX_PAGES': 2,
            'MIN_DELAY': 1.0,
            'MAX_DELAY': 2.0,
        },
    },
}

STRIPE = {
    'SECRET_KEY': env('STRIPE_SECRET_KEY', default=''),
    'PUBLISHABLE_KEY': env('STRIPE_PUBLISHABLE_KEY', default=''),
    'WEBHOOK_SECRET': env('STRIPE_WEBHOOK_SECRET', default=''),
    'API_BASE_URL': env('STRIPE_API_BASE_URL', default='https://api.stripe.com'),
    'SUCCESS_URL': env(
        'STRIPE_SUCCESS_URL',
        default=f'{FRONTEND_PUBLIC_URL.rstrip("/")}/billing/success?session_id={{CHECKOUT_SESSION_ID}}',
    ),
    'CANCEL_URL': env(
        'STRIPE_CANCEL_URL',
        default=f'{FRONTEND_PUBLIC_URL.rstrip("/")}/billing/cancel',
    ),
    'PORTAL_RETURN_URL': env(
        'STRIPE_PORTAL_RETURN_URL',
        default=f'{FRONTEND_PUBLIC_URL.rstrip("/")}/billing',
    ),
    'PRICE_IDS': {
        'pro': {
            'monthly': env('STRIPE_PRICE_PRO_MONTHLY', default=''),
            'yearly': env('STRIPE_PRICE_PRO_YEARLY', default=''),
        },
    },
}

