"""
Django settings for project project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
import os
from datetime import timedelta
from pathlib import Path

import environ
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Load environment variables from .env file
env = environ.Env(
    DEBUG=(bool, False)
)
environ.Env.read_env(os.path.join(BASE_DIR, '.env'))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('DJANGO_SECRET_KEY', default='django-insecure-v6m^+o5n4+%-_yxh6-hrt1h(75@lnt%gsng2(!v-kkj!vnx$h(')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env('DJANGO_DEBUG', default=True)

ALLOWED_HOSTS = env.list('ALLOWED_HOSTS', default=['*'])
CSRF_TRUSTED_ORIGINS = env.list("CSRF_TRUSTED_ORIGINS", default=[])


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt',
    'django_filters',
    'hunter',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            BASE_DIR / 'base_template'
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / 'base_static'] if (BASE_DIR / 'base_static').exists() else []
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

STATIC_ROOT = BASE_DIR / "staticfiles"
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.BasicAuthentication',
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_PAGINATION_CLASS': 'hunter.pagination.HunterPagination',
    'PAGE_SIZE': 10,
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ],
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
    'AUTH_HEADER_TYPES': ('Bearer',),
}

JOB_AGGREGATION = {
    'PROVIDER_ORDER': ['remotive', 'greenhouse', 'lever', 'ashby', 'remoteok', 'weworkremotely', 'indeed'],
    'DEFAULTS': {
        'TIMEOUT': 10,
        'MAX_PAGES': 1,
        'MIN_DELAY': 0.0,
        'MAX_DELAY': 0.0,
        'MAX_RETRIES': 2,
        'TRUST_ENV': False,
    },
    'PROVIDERS': {
        'remotive': {
            'ENABLED': True,
            'MAX_PAGES': 1,
            'MIN_DELAY': 0.0,
            'MAX_DELAY': 0.0,
        },
        'greenhouse': {
            'ENABLED': True,
            'BOARD_TOKENS': [
                {'token': 'canonical', 'company': 'Canonical'},
            ],
        },
        'lever': {
            'ENABLED': True,
            'SITES': [
                {'site': 'bighealth', 'company': 'Big Health'},
                {'site': 'dnb', 'company': 'Dun & Bradstreet'},
            ],
        },
        'ashby': {
            'ENABLED': True,
            'JOB_BOARDS': [
                {'board': 'openai', 'company': 'OpenAI'},
            ],
        },
        'remoteok': {
            'ENABLED': False,
            'MAX_PAGES': 1,
            'MIN_DELAY': 0.0,
            'MAX_DELAY': 0.0,
        },
        'weworkremotely': {
            'ENABLED': False,
            'MAX_PAGES': 1,
            'MIN_DELAY': 0.0,
            'MAX_DELAY': 0.0,
        },
        'indeed': {
            'ENABLED': False,
            'MAX_PAGES': 2,
            'MIN_DELAY': 1.0,
            'MAX_DELAY': 2.0,
        },
    },
}

STRIPE = {
    'SECRET_KEY': env('STRIPE_SECRET_KEY', default=''),
    'PUBLISHABLE_KEY': env('STRIPE_PUBLISHABLE_KEY', default=''),
    'WEBHOOK_SECRET': env('STRIPE_WEBHOOK_SECRET', default=''),
    'API_BASE_URL': env('STRIPE_API_BASE_URL', default='https://api.stripe.com'),
    'SUCCESS_URL': env(
        'STRIPE_SUCCESS_URL',
        default='http://localhost:3000/billing/success?session_id={CHECKOUT_SESSION_ID}',
    ),
    'CANCEL_URL': env(
        'STRIPE_CANCEL_URL',
        default='http://localhost:3000/billing/cancel',
    ),
    'PORTAL_RETURN_URL': env(
        'STRIPE_PORTAL_RETURN_URL',
        default='http://localhost:3000/settings/billing',
    ),
    'PRICE_IDS': {
        'pro': {
            'monthly': env('STRIPE_PRICE_PRO_MONTHLY', default=''),
            'yearly': env('STRIPE_PRICE_PRO_YEARLY', default=''),
        },
    },
}

